binance:
  api:
    BTCUSDT:
      api:
        ETHUSDT:
bitfinex:
  api:
    tBTCUSD: {}
    tETHUSD: {}
bitflyer:
  api:
    BTC_JPY:
    ETH_JPY: {}
bitmex:
  api:
    XBTUSD: {}
    ETHUSD: {}
bybit:
  api:
    BTCUSD: {}
    ETHUSD: {}
coinbase:
  api:
    "BTC-USD":
      - aggregate
      - candles:
        timeframe: "1m"
        top_n: 25
    "ETH-USD": {}
ftx:
  api:
    "BTC/USD": {}
    "ETH/USD": {} 
    "BTC-PERP": {} 
    "ETH-PERP": {} 
    "BTC-MOVE":
      futures: true
