import pandas as pd

GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
FIREBASE_ADMIN_CREDENTIALS = "FIREBASE_ADMIN_CREDENTIALS"
PROJECT_ID = "PROJECT_ID"
FIRESTORE_COLLECTIONS = "FIRESTORE_COLLECTIONS"
BIGQUERY_LOCATION = "BIGQUERY_LOCATION"
BIGQUERY_DATASET = "BIGQUERY_DATASET"
BIGQUERY_TABLES = "BIGQUERY_TABLES"

BIGQUERY_HOT = pd.Timedelta("2d")

GCP_APPLICATION_CREDENTIALS = (
    GOOGLE_APPLICATION_CREDENTIALS,
    FIREBASE_ADMIN_CREDENTIALS,
)

BINANCE_API_KEY = "BINANCE_API_KEY"

PRODUCTION_ENV_VARS = (
    PROJECT_ID,
    BIGQUERY_LOCATION,
    BIGQUERY_DATASET,
    BINANCE_API_KEY,
)
