DAILY = "D"
WEEKLY = "W"
MONTHLY = "M"
QUARTERLY = "Q"
YEARLY = "Y"

ERA_LENGTHS = (DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY)

VOLUME = "volume"
NOTIONAL = "notional"
TICKS = "ticks"

CUMSUM_ATTRS = (VOLUME, NOTIONAL, TICKS)
