BITFLYER = "bitflyer"

BITFLYER_MAX_REQUESTS_RESET = "BITFLYER_MAX_REQUESTS_RESET"
BITFLYER_TOTAL_REQUESTS = "BITFLYER_TOTAL_REQUESTS"

URL = "https://api.bitflyer.com/v1/"
MAX_REQUESTS = 500
MAX_REQUESTS_RESET = 300  # 5 minutes
MAX_RESULTS = 100
MIN_ELAPSED_PER_REQUEST = 0
